apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    role: hello-world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: hello-world
    spec:
      containers:
      - name: hello
        image: nginxdemos/hello:latest
        ports:
        - containerPort: 80